### PR TITLE
Fix NPE when using replaceInputText

### LINKED ISSUE #262: NullPointerException when using ResponseAction.replaceInputText()
With the addition of the StateSnapshot and generic click handler, the [null check](https://github.com/WesJD/AnvilGUI/blob/5e8eac0ad89a9fc07dc1eb2cdd03469121cae408/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java#L245) on the clicked item has been removed and now if a player would click into the empty output slot because he has not yet changed the text and the ClickHandler would return ResponseAction.replaceInputText(), a NullPointerException would be thrown because it [tries to clone](https://github.com/WesJD/AnvilGUI/blob/1586ce6fe0efcec514429d37fdc795d923505df1/api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java#L464) the contents of the output slot.

Why is the current behavior that the output is cloned and renamed and then put into the input instead of just renaming the input in place?

### PR DESCRIPTION
**Pull request by Sytm**
Should we handle it like this, or rename the left input slot in place instead?

Fixes #262

### CODE REVIEW

File: api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java [hunk 1]
```diff
@@ -461,12 +461,20 @@ public interface ResponseAction extends BiConsumer<AnvilGUI, Player> {
...
-                final ItemStack outputSlotItem =
-                        anvilgui.getInventory().getItem(Slot.OUTPUT).clone();
-                final ItemMeta meta = outputSlotItem.getItemMeta();
+                ItemStack item = anvilgui.getInventory().getItem(Slot.OUTPUT);
+                if (item == null) {
+                    // Fallback on left input slot if player hasn't typed anything yet
+                    item = anvilgui.getInventory().getItem(Slot.INPUT_LEFT);
+                }
+                if (item == null) {
+                    return; // Do nothing if left input slot is also empty
```
Comment (WesJD) [inline api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java:470]: Do you think that this should instead throw an exception? After all, the developer is stating to change the input text, but there is no input text to change...

**Review by WesJD — CHANGES_REQUESTED** [review]

**Comment by WesJD** [comment]
lgtm. Update version to `1.6.6-SNAPSHOT`
