### PR TITLE
Send experience packets to support Bedrock via Geyser

### LINKED ISSUE #332: AnvilGUI doesn't work for bedrock players
AnvilGUI does not display correctly for bedrock players.

I can't click on the result item because it says "Enchantment Cost: 1"

In the image below, on the left is the Bedrock player's view and on the right is the Java player's view.
image

I'm using version 1.9.4-SNAPSHOT of AnvilGUI and the code is this:
```java
        new AnvilGUI.Builder()
                    .plugin(LFAuctionHousePlugin.getInstance())
                    .title("Starting bid:")
                    .itemLeft(new ItemStack(Material.PAPER))
                    .onClose(stateSnapshot -> TaskUtil.runSyncSafe(() -> inventoryController.inventoryFactory.getAHSellInventory(new AHSellInventory(data, profile, guild)).open(stateSnapshot.getPlayer())))
                    .text("0")
                    .onClick((slot, stateSnapshot) -> {
                        var localPlayer = stateSnapshot.getPlayer();
                        var response = stateSnapshot.getText();

                        localPlayer.sendMessage(response);

                        if (response.isEmpty()) {
                            TaskUtil.runSyncSafe(() -> inventoryController.inventoryFactory.getAHSellInventory(new AHSellInventory(data, profile, guild)).open(localPlayer));
                            return AnvilGUI.Response.close();
                        }

                        try {
                            var price = BigDecimal.valueOf(MathUtil.parseSuffixedCurrency(response));

                            if (itemController.isDeniedItemPrice(player, price)) {
                                return AnvilGUI.Response.close();
                            }

                            data.setPrice(price);
                            TaskUtil.runTask(() -> inventoryController.inventoryFactory.getAHSellInventory(new AHSellInventory(data, profile, guild)).open(localPlayer));
                        } catch (Exception e) {
                            UtilMessages.sendMessage(player, PREFIX, false, "Invalid number!");
                        }

                        return AnvilGUI.Response.close();
                    })
                    .open(player);
```

### PR DESCRIPTION
**Pull request by PikaMug**
Fixes #332 

Bedrock does not allow the result slot to be clicked when the player's experience level is 0. This change sends a packet which sets the Bedrock client's level to 20 (number is trivial) on anvil open, and then again back to the actual value when closed. It adds a `.gesyer-compat(boolean)` to the builder, which is enabled by default. A second constructor has been added to AnvilGUI for backwards compatibility.

In writing this, it occurs to me it may be preferred to have the method be something like `.disableGeyserCompat()` instead, to match `.preventClose()`. Let me know if that's what you'd prefer.

Other changes I made in order to test this:
- Removed jvm.config. As mentioned in #329 it is no longer required with the newer version of Spotless we're on, see https://github.com/diffplug/spotless/blob/main/plugin-maven/CHANGES.md#2227---2022-06-10
- ~~Added a jitpack.yml file which allows AnvilGUI to be compiled on the popular [jitpack.io](https://www.jitpack.io/) repository~~

### CODE REVIEW

File: api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java [hunk 1]
```diff
@@ -27,6 +27,7 @@
 import org.bukkit.inventory.ItemStack;
 import org.bukkit.inventory.meta.ItemMeta;
 import org.bukkit.plugin.Plugin;
+import org.geysermc.geyser.api.GeyserApi;
```
Comment (WesJD) [inline api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java:30]: won't this import break all usages of the library on servers without the geyser plugin installed?

i believe you will need a separate class like the wrapper classes and you only instantiate it if geyser is installed

File: api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java [hunk 2]
```diff
@@ -122,6 +126,46 @@ private static ItemStack itemNotNull(ItemStack stack) {
...
+     * @param mainThreadExecutor  An {@link Executor} that executes on the main server thread
+     * @param titleComponent      What to have the text already set to
+     * @param initialContents     The initial contents of the inventory
+     * @param preventClose        Whether to prevent the inventory from closing
+     * @param geyserCompatibility Whether to enable compatibility with Geyser software
+     * @param closeListener       A {@link Consumer} when the inventory closes
+     * @param concurrentClickHandlerExecution Flag to allow concurrent execution of the click handler
+     * @param clickHandler        A {@link ClickHandler} that is called when the player clicks a slot
+     */
+    private AnvilGUI(
```
Comment (WesJD) [inline api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java:140]: there is no need to add a new constructor here, because the constructor is private and only used in the builder. you can safely just edit the old constructor.

File: api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java [hunk 3]
```diff
@@ -430,6 +497,14 @@ public Builder preventClose() {
             return this;
         }
 
+        /**
+         * Toggles compatibility with Geyser software
+         */
+        public Builder geyserCompat(boolean enabled) {
```
Comment (WesJD) [inline api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java:503]: as you mentioned `disableGeyserCompat` would make more sense considering its enabled by default

File: jitpack.yml [hunk 4]
```diff
@@ -0,0 +1,6 @@
+# Tell Jitpack to build using Java 21 (defaults to 8)
```
Comment (WesJD) [inline jitpack.yml:1]: this should be done in a separate PR

**Review by WesJD — CHANGES_REQUESTED** [review]

File: api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java (hunk 1 above)
Comment (PikaMug) [reply api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java:30]: That was not the case in my testing on a 1.21 Paper server with the only plugins being Geyser, Floodgate, and a modified version of [Quests](https://github.com/PikaMug/Quests) with this PR shaded in. Removing Geyser and Floodgate did not affect the ability to open AnvilGUIs.

Comment (WesJD) [reply api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java:30]: sweet

**Comment by WesJD** [comment]
final thing to do then is just increment the minor version and we're good to merge

**Review by WesJD — APPROVED** [review]

**Comment by WesJD** [comment]
Thank you for your help!
